# Generated by Django 4.2.13 on 2024-07-05 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_generate_missing_fingerprint"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="unix_username",
            field=models.CharField(
                help_text="A short, unique name for you. It will be used to form your local username on any systems. Should only contain lower-case letters and digits and must start with a letter.",
                max_length=50,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Must start with a letter and only contain numbers and letters.",
                        regex="^[a-z][a-z0-9]+$",
                    ),
                    django.core.validators.RegexValidator(
                        inverse_match=True, regex="(admin)|(root)$"
                    ),
                    django.core.validators.MinLengthValidator(5),
                    django.core.validators.MaxLengthValidator(20),
                ],
                verbose_name="UNIX username",
            ),
        ),
    ]
