# Generated by Django 6.0.8 on 2026-09-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_notificationtemplate_path_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="slug",
            field=models.SlugField(blank=True, default=None, null=True),
        ),
    ]
