# Generated by Django 6.0.8 on 2026-10-05 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_alter_user_slug"),
        ("core", "0051_telemetry_opt_out"),
    ]

    operations = []
