# Generated by Django 4.2.24 on 2025-11-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proposal", "0046_alter_call_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="stale_reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the stale proposal reminder email was sent",
                null=True,
            ),
        ),
    ]
