# Generated by Django 4.2.24 on 2025-11-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proposal", "0047_proposal_stale_reminder_sent_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProposalIDGenerator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        db_index=True,
                        help_text="The year for which this generator creates IDs.",
                        unique=True,
                        verbose_name="year",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The current count of proposals created in this year.",
                        verbose_name="count",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposal ID Generator",
                "verbose_name_plural": "Proposal ID Generators",
                "ordering": ["-year"],
            },
        ),
    ]
