# Generated by Django 4.2.24 on 2025-11-25 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proposal", "0048_proposalidgenerator"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="minimum_required_uploads",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Minimum number of documents required to submit a proposal. Set to 0 for no requirement.",
            ),
        ),
    ]
