# Generated by Django 4.2.24 on 2025-12-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proposal", "0049_round_minimum_required_uploads"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="submitted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the proposal was submitted",
                null=True,
            ),
        ),
    ]
