# Generated by Django 4.2.24 on 2026-01-23 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import waldur_core.core.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("proposal", "0050_proposal_submitted_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProposalResourceAdjustment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("modify", "Modify limits"),
                            ("remove", "Remove from allocation"),
                            ("add", "Add new resource"),
                        ],
                        default="modify",
                        max_length=20,
                    ),
                ),
                ("adjusted_attributes", models.JSONField(blank=True, default=dict)),
                ("adjusted_limits", models.JSONField(blank=True, default=dict)),
                ("comment", models.TextField(blank=True)),
                (
                    "call_offering",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proposal.requestedoffering",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_adjustments",
                        to="proposal.proposal",
                    ),
                ),
                (
                    "requested_resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="proposal.requestedresource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposal resource adjustment",
                "verbose_name_plural": "Proposal resource adjustments",
                "ordering": ["-created"],
            },
        ),
    ]
