# Generated by Django 4.2.24 on 2026-05-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proposal", "0051_proposalresourceadjustment"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="notes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Append-only list of {timestamp, author, text} notes visible only to call managers and staff.",
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="default_allowed_domains",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Default list of email domain glob patterns allowed to join projects on the remote portal.",
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="default_membership_control",
            field=models.CharField(
                blank=True,
                choices=[
                    ("open", "Open — receiving portal manages membership freely"),
                    ("members_only", "Members only — roles are authoritative"),
                    ("roles_only", "Roles only — membership is authoritative"),
                    ("locked", "Locked — both membership and roles are authoritative"),
                ],
                help_text="Default membership control policy applied to RemoteProjects created from proposals in this round.",
                max_length=16,
                null=True,
            ),
        ),
    ]
