# Generated by Django 4.2.24 on 2026-06-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proposal", "0052_proposal_notes_round_default_allowed_domains_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="default_reapply_text",
            field=models.CharField(
                blank=True,
                help_text="Link text for the reapply URL shown to successful applicants.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="default_reapply_url",
            field=models.URLField(
                blank=True,
                help_text="URL for successful applicants to reapply for new time or a follow-on application.",
                null=True,
            ),
        ),
    ]
