# Generated by Django 4.2.24

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import waldur_core.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("proposal", "0053_round_default_reapply_text_round_default_reapply_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="formbricks_flow_key",
            field=models.CharField(
                blank=True,
                help_text="Key into FORM_FLOWS selecting this call's Formbricks survey chain. "
                "Leave blank to use the legacy Waldur-native proposal form.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="FormStepResponse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("step_key", models.CharField(max_length=100)),
                ("survey_id", models.CharField(max_length=100)),
                ("response_id", models.CharField(max_length=100)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("question_labels", models.JSONField(blank=True, default=dict)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_step_responses",
                        to="proposal.proposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form step response",
                "verbose_name_plural": "Form step responses",
            },
        ),
        migrations.AlterUniqueTogether(
            name="formstepresponse",
            unique_together={("proposal", "step_key")},
        ),
    ]
