# Generated by Django 4.2.24 on 2026-08-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proposal", "0053_round_default_reapply_text_round_default_reapply_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="fixed_review_end_date",
            field=models.DateTimeField(
                blank=True,
                help_text="If set, every review in this round uses this as its review_end_date instead of created + review_duration_in_days. Set to null to revert to the review_duration_in_days behaviour.",
                null=True,
            ),
        ),
    ]
