# Generated by Django 6.0.8 on 2026-09-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proposal", "0080_call_support_ticket_caller"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProposalIDGenerator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(unique=True)),
                (
                    "count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The last sequence number issued for this year.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposal ID generator",
                "ordering": ["-year"],
            },
        ),
    ]
