# Generated by Django 6.0.8 on 2026-10-05 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proposal", "0081_proposal_id_generator"),
        ("proposal", "0085_proposal_submitted_at"),
    ]

    operations = []
