# Generated by Django 4.2.17 on 2024-12-11 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("waldur_openportal", "0001_setup_openportal"),
    ]

    operations = [
        migrations.AddField(
            model_name="association",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="op-associations-user+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="command",
            field=models.TextField(
                blank=True, help_text="Command being run via OpenPortal", null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="report",
            field=models.TextField(blank=True, null=True, verbose_name="Job output"),
        ),
        migrations.AddField(
            model_name="job",
            name="runtime_state",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="job",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to user which submitted job",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="op-jobs-user+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="allocation",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="structure.project",
            ),
        ),
        migrations.AlterField(
            model_name="allocation",
            name="service_settings",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="structure.servicesettings",
            ),
        ),
        migrations.AlterField(
            model_name="allocationuserusage",
            name="allocation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="op-allocationuser-allocation+",
                to="waldur_openportal.allocation",
            ),
        ),
        migrations.AlterField(
            model_name="allocationuserusage",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="op-allocationuser-user+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="association",
            name="allocation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="op-associations-allocation+",
                to="waldur_openportal.allocation",
            ),
        ),
    ]
