# Generated by Django 4.2.17 on 2024-12-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waldur_openportal', '0002_association_user_job_command_job_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='username',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
