# Generated by Django 4.2.17 on 2025-01-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waldur_openportal', '0003_alter_association_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='groupname',
            field=models.TextField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='association',
            name='useridentifier',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
