# Generated by Django 4.2.17 on 2025-01-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waldur_openportal', '0004_allocation_groupname_association_useridentifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='groupname',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
