# Generated by Django 4.2.18 on 2025-01-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waldur_openportal', '0006_userinfo_projectinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='node_usage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='allocationuserusage',
            name='node_usage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
