# Generated by Django 4.2.18 on 2025-01-27 08:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waldur_openportal', '0007_alter_allocation_node_usage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_usage', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('is_complete', models.BooleanField(default=False)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='op-historicalallocation+', to='waldur_openportal.allocation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
