# Generated by Django 4.2.18 on 2025-01-31 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_openportal", "0008_historicalallocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocation",
            name="is_added",
            field=models.BooleanField(default=False),
        ),
    ]
