# Generated by Django 4.2.18 on 2025-04-08 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_openportal", "0009_allocation_is_added"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectNotification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="How many days between notifications (0 = no notifications).",
                        verbose_name="frequency",
                    ),
                ),
                (
                    "last_notification",
                    models.DateField(
                        blank=True,
                        help_text="When was the last notification sent?",
                        null=True,
                        verbose_name="last notification",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="op-projectnotification-project+",
                        to="structure.project",
                    ),
                ),
            ],
        ),
    ]
