# Generated by Django 4.2.21 on 2025-06-03 08:48

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_openportal", "0010_projectnotification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.CharField(
                        db_index=True, max_length=36, unique=True, verbose_name="ID"
                    ),
                ),
                (
                    "job_data",
                    models.TextField(
                        blank=True,
                        help_text="JSON representation of the job",
                        null=True,
                        verbose_name="job data",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("communicated", "Communicated"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="The current status of the job.",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="allocation",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (5, "CREATION_SCHEDULED"),
                    (6, "CREATING"),
                    (1, "UPDATE_SCHEDULED"),
                    (2, "UPDATING"),
                    (7, "DELETION_SCHEDULED"),
                    (8, "DELETING"),
                    (3, "OK"),
                    (4, "ERRED"),
                ],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="projectnotification",
            name="frequency",
            field=models.PositiveSmallIntegerField(
                default=14,
                help_text="How many days between notifications (0 = no notifications).",
                verbose_name="frequency",
            ),
        ),
    ]
