# Generated by Django 4.2.21 on 2025-06-04 07:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("structure", "0053_alter_project_short_name"),
        ("waldur_openportal", "0011_job_alter_allocation_state_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectShortNameGenerator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shortname",
                    models.CharField(
                        help_text="The key / descriptor used to identify this generator.",
                        max_length=30,
                        unique=True,
                        verbose_name="shortname",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The number of projects created with this shortname.",
                        verbose_name="count",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="job",
            name="created",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="The date when this job was created.",
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ManagedProject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        db_index=True, max_length=64, unique=True, verbose_name="ID"
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="JSON representation of the project",
                        null=True,
                        verbose_name="project data",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="op-managedproject-project+",
                        to="structure.project",
                        verbose_name="project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectClass",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=128, verbose_name="name"
                    ),
                ),
                (
                    "portal",
                    models.CharField(
                        db_index=True, max_length=32, verbose_name="portal"
                    ),
                ),
                (
                    "shortname",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="shortname"
                    ),
                ),
                (
                    "resources",
                    models.TextField(
                        blank=True,
                        help_text="A comma-separated list of OpenPortal resource identifiers that should be created automatically for projects created in this class by the specified portal.",
                        null=True,
                        verbose_name="resources",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="The organisation that this project class belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="op-projectclass-organisation+",
                        to="structure.customer",
                        verbose_name="organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Class",
                "verbose_name_plural": "Project Classes",
                "unique_together": {("name", "portal")},
            },
        ),
    ]
