# Generated by Django 4.2.21 on 2025-06-05 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "waldur_openportal",
            "0012_projectshortnamegenerator_job_created_managedproject_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="managedproject",
            name="local_identifier",
            field=models.CharField(
                blank=True,
                help_text="The local project identifier in this portal.",
                max_length=64,
                null=True,
                verbose_name="local ID",
            ),
        ),
        migrations.AddField(
            model_name="managedproject",
            name="project_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="op-managedproject-projectclass+",
                to="waldur_openportal.projectclass",
                verbose_name="project class",
            ),
        ),
    ]
