# Generated by Django 4.2.21 on 2025-06-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0163_remove_order_activated"),
        ("waldur_openportal", "0013_managedproject_local_identifier_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectclass",
            name="resources",
        ),
        migrations.AddField(
            model_name="projectclass",
            name="offerings",
            field=models.ManyToManyField(
                help_text="The list of MarketPlace Offerings that should be created automatically for projects created in this class by the specified portal.",
                related_name="op-projectclass-offerings+",
                to="marketplace.offering",
                verbose_name="offerings",
            ),
        ),
    ]
