# Generated by Django 4.2.21 on 2025-06-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "waldur_openportal",
            "0014_remove_projectclass_resources_projectclass_offerings",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OnceTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_name",
                    models.CharField(
                        db_index=True,
                        max_length=128,
                        unique=True,
                        verbose_name="task name",
                    ),
                ),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date when this task was started.",
                        null=True,
                        verbose_name="run date",
                    ),
                ),
            ],
        ),
    ]
