# Generated by Django 4.2.23 on 2025-06-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_openportal", "0016_remoteallocation_remoteassociation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectclass",
            name="approval_limit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The credit limit beyond which requests need to be approved by a local admin. If this is None, then no local approval is required. If this is set to 0, then all requests (including creating the project) need to be approved.",
                max_digits=20,
                null=True,
                verbose_name="approval limit",
            ),
        ),
        migrations.AddField(
            model_name="projectclass",
            name="max_credit_limit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The maximum credit limit for any projects created in this class. Any requests beyond this limit are automatically rejected. If this is None, then no maximum limit is set. If this is set to 0, then no projects can be created in this class.",
                max_digits=20,
                null=True,
                verbose_name="maximum credit limit",
            ),
        ),
        migrations.AddField(
            model_name="projectclass",
            name="role_mapping",
            field=models.JSONField(
                default=dict,
                help_text="The mapping of role names from the remote portal to role names in this portal for users in projects created in this class.",
                verbose_name="role mapping",
            ),
        ),
    ]
