# Generated by Django 4.2.23 on 2025-06-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_openportal", "0017_projectclass_approval_limit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="managedproject",
            name="needs_approval",
            field=models.BooleanField(
                default=False,
                help_text="Whether or not a change to this project needs approval from a local admin.",
                verbose_name="needs approval",
            ),
        ),
    ]
