# Generated by Django 4.2.23 on 2025-06-24 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("waldur_openportal", "0018_managedproject_needs_approval"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="managedproject",
            name="needs_approval",
        ),
        migrations.AddField(
            model_name="managedproject",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="managedproject",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="managedproject",
            name="review_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="managedproject",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="managedproject",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="managedproject",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (1, "draft"),
                    (2, "pending"),
                    (3, "approved"),
                    (4, "rejected"),
                    (5, "canceled"),
                ],
                default=1,
            ),
        ),
    ]
