# Generated by Django 4.2.23 on 2025-06-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_openportal", "0019_remove_managedproject_needs_approval_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="remoteallocation",
            name="local_version",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The local version of the remote project. This is used to track changes to the project.",
                verbose_name="local version",
            ),
        ),
        migrations.AddField(
            model_name="remoteallocation",
            name="remote_version",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The last successful updated version of the remote project. This is used to track changes to the project.",
                verbose_name="remote version",
            ),
        ),
    ]
