# Generated by Django 4.2.23 on 2025-07-09 11:16

from django.db import migrations
import waldur_core

# This migration adds a UUID field to the ProjectClass model.
# Note that this will fail if you have any existing ProjectClass objects...


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_openportal", "0020_remoteallocation_local_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectclass",
            name="uuid",
            field=waldur_core.core.fields.UUIDField(),
        ),
    ]
