# Generated by Django 4.2.23 on 2025-07-11 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_openportal", "0021_auto_20250709_1116"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectclass",
            name="provider",
            field=models.ForeignKey(
                default=1,
                help_text="The organisation that owns this project class.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="op-projectclass-provider+",
                to="structure.customer",
                verbose_name="provider",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="managedproject",
            name="details",
            field=models.JSONField(
                blank=True,
                help_text="JSON representation of the project",
                null=True,
                verbose_name="project data",
            ),
        ),
    ]
