# Generated by Django 4.2.23 on 2025-07-17 02:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "waldur_openportal",
            "0022_projectclass_provider_alter_managedproject_details",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProjectClass",
            new_name="ProjectTemplate",
        ),
        migrations.RenameField(
            model_name="managedproject",
            old_name="project_class",
            new_name="project_template",
        ),
    ]
