# Generated by Django 4.2.23 on 2025-07-17 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("structure", "0054_merge_20250612_0633"),
        ("waldur_openportal", "0023_rename_projectclass_projecttemplate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="managedproject",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="op-managedproject-project+",
                to="structure.project",
                verbose_name="project",
            ),
        ),
        migrations.AlterField(
            model_name="managedproject",
            name="project_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="op-managedproject-projectclass+",
                to="waldur_openportal.projecttemplate",
                verbose_name="project class",
            ),
        ),
        migrations.AlterField(
            model_name="projecttemplate",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="The organisation that this project class belongs to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="op-projectclass-organisation+",
                to="structure.customer",
                verbose_name="organisation",
            ),
        ),
        migrations.AlterField(
            model_name="projecttemplate",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                help_text="The organisation that owns this project class.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="op-projectclass-provider+",
                to="structure.customer",
                verbose_name="provider",
            ),
        ),
        migrations.AlterField(
            model_name="projecttemplate",
            name="role_mapping",
            field=models.JSONField(
                default=dict,
                help_text="The mapping of role names from the remote portal to role information in this portal for users in projects created in this class.",
                verbose_name="role mapping",
            ),
        ),
    ]
