# Generated by Django 4.2.23 on 2025-07-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_openportal", "0024_alter_managedproject_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttemplate",
            name="allocation_units_mapping",
            field=models.JSONField(
                default=dict,
                help_text="The mapping of allocation units to credits, i.e. how many credits to award per GPU hour allocated etc.",
                verbose_name="allocation units mapping",
            ),
        ),
    ]
