# Generated by Django 4.2.23 on 2025-07-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_openportal", "0025_projecttemplate_allocation_units_mapping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projecttemplate",
            name="allocation_units_mapping",
            field=models.JSONField(
                default=dict,
                help_text="The mapping of credits to allocation units, i.e. how many allocation units to award per credit allocated.",
                verbose_name="allocation units mapping",
            ),
        ),
    ]
