# Generated by Django 4.2.23 on 2025-07-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_openportal", "0026_alter_projecttemplate_allocation_units_mapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="managedproject",
            name="destination",
            field=models.CharField(
                blank=True,
                help_text="The destination used to send instructions from the remote portal.",
                max_length=256,
                null=True,
                verbose_name="destination",
            ),
        ),
    ]
