# Generated by Django 4.2.23 on 2025-08-12 09:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_openportal", "0027_managedproject_destination"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RemoteAllocationUserUsage",
        ),
    ]
