# Generated by Django 4.2.24 on 2026-03-13 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_openportal", "0034_cachedprojectusagereport"),
    ]

    operations = [
        migrations.CreateModel(
            name="CachedProjectStorageReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("project_identifier", models.CharField(max_length=64)),
                ("resource", models.CharField(max_length=256)),
                ("report", models.JSONField()),
            ],
            options={
                "unique_together": {
                    ("year", "month", "project_identifier", "resource")
                },
            },
        ),
    ]
