# Generated by Django 4.2.24 on 2026-03-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_openportal", "0035_cachedprojectstoragereport"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cachedprojectstoragereport",
            index=models.Index(
                fields=["project_identifier"], name="waldur_open_project_077226_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cachedprojectusagereport",
            index=models.Index(
                fields=["project_identifier"], name="waldur_open_project_c1652b_idx"
            ),
        ),
    ]
