# Generated by Django 4.2.24 on 2026-03-31 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import waldur_core.core.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("structure", "0067_merge_20251110_0435"),
        (
            "waldur_openportal",
            "0036_cachedprojectstoragereport_waldur_open_project_077226_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RemoteProject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "destination",
                    models.CharField(
                        help_text="Routing path from the local portal to the remote resource, e.g. 'airr.brics.isambard-ai'.  Never changes after creation.",
                        max_length=256,
                        verbose_name="destination",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="Stable remote project identifier, e.g. 'u6ac.brics'.  Uniquely identifies the project on the remote portal and never changes.",
                        max_length=64,
                        verbose_name="identifier",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("stale", "Stale"),
                            ("error", "Error"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="state",
                    ),
                ),
                (
                    "last_sent_details",
                    models.JSONField(
                        blank=True,
                        help_text="The AwardDetails most recently sent to the remote portal (create_award or update_award).  May not yet be confirmed.",
                        null=True,
                        verbose_name="last sent award details",
                    ),
                ),
                (
                    "last_confirmed_details",
                    models.JSONField(
                        blank=True,
                        help_text="The AwardDetails most recently confirmed by the remote portal.  Reflects what is actually live on the remote portal.",
                        null=True,
                        verbose_name="last confirmed award details",
                    ),
                ),
                (
                    "pending_details",
                    models.JSONField(
                        blank=True,
                        help_text="AwardDetails that have been submitted to the remote portal but are awaiting human review or confirmation (e.g. an allocation increase that requires manual approval).  Null when nothing is pending.",
                        null=True,
                        verbose_name="pending award details",
                    ),
                ),
                (
                    "pending_since",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the currently pending change was submitted.",
                        null=True,
                        verbose_name="pending since",
                    ),
                ),
                (
                    "current_allocation",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Latest confirmed allocation (credits) for this project.  Updated whenever a RemoteProjectAllocationEntry is confirmed.",
                        max_digits=20,
                        verbose_name="current allocation",
                    ),
                ),
                (
                    "pending_allocation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Allocation value currently under review on the remote portal.  Null when no allocation change is pending.",
                        max_digits=20,
                        null=True,
                        verbose_name="pending allocation",
                    ),
                ),
                (
                    "last_contact_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="The most recent time the remote portal acknowledged anything about this project (confirmation, usage report, get_award response, etc.).  Used to detect connectivity issues and to trigger a transition to the STALE state.",
                        null=True,
                        verbose_name="last contact time",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "current_project",
                    models.ForeignKey(
                        blank=True,
                        help_text="The local Waldur project currently holding this award.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_remote_projects",
                        to="structure.project",
                        verbose_name="current project",
                    ),
                ),
                (
                    "remote_allocation",
                    models.OneToOneField(
                        blank=True,
                        help_text="The current RemoteAllocation that drives this project.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remote_project",
                        to="waldur_openportal.remoteallocation",
                        verbose_name="remote allocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remote Project",
                "verbose_name_plural": "Remote Projects",
                "unique_together": {("destination", "identifier")},
            },
        ),
        migrations.CreateModel(
            name="RemoteProjectAllocationEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocation",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="New total allocation (credits) after this change.",
                        max_digits=20,
                        verbose_name="allocation",
                    ),
                ),
                (
                    "previous_allocation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total allocation before this change.  Null for the first entry.",
                        max_digits=20,
                        null=True,
                        verbose_name="previous allocation",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="submitted at"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the remote portal confirmed this allocation.  Null if pending.",
                        null=True,
                        verbose_name="confirmed at",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Optional comment, e.g. 'carrying over 20 unused credits from previous award'.",
                        verbose_name="note",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remote Project Allocation Entry",
                "verbose_name_plural": "Remote Project Allocation Entries",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="RemoteProjectAuditEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="timestamp"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("award_created", "Award created (create_award sent)"),
                            (
                                "award_confirmed",
                                "Award creation confirmed by remote portal",
                            ),
                            ("award_updated", "Award updated (update_award sent)"),
                            (
                                "award_update_confirmed",
                                "Award update confirmed by remote portal",
                            ),
                            (
                                "award_update_rejected",
                                "Award update rejected by remote portal",
                            ),
                            (
                                "award_fetched",
                                "Award details fetched from remote portal (get_award)",
                            ),
                            ("allocation_changed", "Allocation changed"),
                            ("allocation_confirmed", "Allocation change confirmed"),
                            ("allocation_rejected", "Allocation change rejected"),
                            (
                                "project_attached",
                                "Remote project attached to a local project",
                            ),
                            (
                                "project_detached",
                                "Remote project detached from a local project",
                            ),
                            ("state_changed", "State changed"),
                            ("resource_deleted", "Local resource deleted"),
                            (
                                "resource_restored",
                                "Local resource restored / reconnected",
                            ),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="event type",
                    ),
                ),
                (
                    "previous_details",
                    models.JSONField(
                        blank=True,
                        help_text="AwardDetails before this event.  Null for creation events.",
                        null=True,
                        verbose_name="previous award details",
                    ),
                ),
                (
                    "new_details",
                    models.JSONField(
                        blank=True,
                        help_text="AwardDetails after this event, or the details being requested.  Null for events that do not change the details.",
                        null=True,
                        verbose_name="new award details",
                    ),
                ),
                (
                    "remote_response",
                    models.JSONField(
                        blank=True,
                        help_text="Raw response received from the remote portal, if applicable.",
                        null=True,
                        verbose_name="remote response",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Optional free-text comment about this event.",
                        verbose_name="note",
                    ),
                ),
                (
                    "allocation_entry",
                    models.ForeignKey(
                        blank=True,
                        help_text="The allocation ledger entry associated with this event, if applicable.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to="waldur_openportal.remoteprojectallocationentry",
                        verbose_name="allocation entry",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who triggered this event, if it was a human action.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="performed by",
                    ),
                ),
                (
                    "remote_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_log",
                        to="waldur_openportal.remoteproject",
                        verbose_name="remote project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remote Project Audit Entry",
                "verbose_name_plural": "Remote Project Audit Entries",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="RemoteProjectAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attached_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="attached at"),
                ),
                (
                    "detached_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Null while this is the current attachment.",
                        null=True,
                        verbose_name="detached at",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Optional comment recorded when the award was attached or moved.",
                        verbose_name="note",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remote_project_attachments",
                        to="structure.project",
                        verbose_name="project",
                    ),
                ),
                (
                    "remote_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="waldur_openportal.remoteproject",
                        verbose_name="remote project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remote Project Attachment",
                "verbose_name_plural": "Remote Project Attachments",
                "ordering": ["-attached_at"],
            },
        ),
        migrations.AddField(
            model_name="remoteprojectallocationentry",
            name="attachment",
            field=models.ForeignKey(
                blank=True,
                help_text="The award attachment period during which this change was made.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allocation_entries",
                to="waldur_openportal.remoteprojectattachment",
                verbose_name="attachment",
            ),
        ),
        migrations.AddField(
            model_name="remoteprojectallocationentry",
            name="remote_project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocation_history",
                to="waldur_openportal.remoteproject",
                verbose_name="remote project",
            ),
        ),
        migrations.AddField(
            model_name="remoteprojectallocationentry",
            name="source_project",
            field=models.ForeignKey(
                blank=True,
                help_text="The local project/award that triggered this allocation change.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="remote_allocation_entries",
                to="structure.project",
                verbose_name="source project",
            ),
        ),
    ]
