# Generated by Django 4.2.24 on 2026-04-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "waldur_openportal",
            "0037_remoteproject_remoteprojectallocationentry_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="remoteproject",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="remoteproject",
            name="allowed_domains",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of email domain glob patterns allowed to join the project on the remote portal, e.g. ['*.ac.uk'].",
                verbose_name="allowed domains",
            ),
        ),
        migrations.AddField(
            model_name="remoteproject",
            name="breakdown",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Free-form allocation breakdown sent to the remote portal, e.g. {'gpu_hours': '500 GPUHR', 'storage': '5 TB'}.",
                verbose_name="allocation breakdown",
            ),
        ),
        migrations.AddField(
            model_name="remoteproject",
            name="earliest_approve",
            field=models.DateTimeField(
                blank=True,
                help_text="Earliest UTC time the remote portal may approve this award. Gives the sender a window to make corrections before provisioning begins.",
                null=True,
                verbose_name="earliest approve",
            ),
        ),
        migrations.AddField(
            model_name="remoteproject",
            name="link_award",
            field=models.JSONField(
                blank=True,
                help_text="Link to the award record on the funder's system.",
                null=True,
                verbose_name="award link",
            ),
        ),
        migrations.AddField(
            model_name="remoteproject",
            name="link_call",
            field=models.JSONField(
                blank=True,
                help_text="Link to the funding call this award came from.",
                null=True,
                verbose_name="call link",
            ),
        ),
        migrations.AddField(
            model_name="remoteproject",
            name="link_project",
            field=models.JSONField(
                blank=True,
                help_text="Link to the project page on the awarding portal.",
                null=True,
                verbose_name="project page link",
            ),
        ),
        migrations.AddField(
            model_name="remoteproject",
            name="link_renewal",
            field=models.JSONField(
                blank=True,
                help_text="Link to where renewal or more time can be requested.",
                null=True,
                verbose_name="renewal link",
            ),
        ),
        migrations.AddField(
            model_name="remoteproject",
            name="membership_control",
            field=models.CharField(
                blank=True,
                choices=[
                    ("open", "Open — receiving portal manages membership freely"),
                    ("members_only", "Members only — roles are authoritative"),
                    ("roles_only", "Roles only — membership is authoritative"),
                    ("locked", "Locked — both membership and roles are authoritative"),
                ],
                help_text="Policy controlling whether the remote portal may independently modify project membership or roles.",
                max_length=16,
                null=True,
                verbose_name="membership control",
            ),
        ),
        migrations.AddField(
            model_name="remoteproject",
            name="notes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Append-only list of timestamped notes {timestamp, author, text} communicated to the remote portal.",
                verbose_name="notes",
            ),
        ),
        migrations.AlterField(
            model_name="remoteproject",
            name="identifier",
            field=models.CharField(
                blank=True,
                help_text="Stable remote project identifier, e.g. 'u6ac.brics'.  Uniquely identifies the project on the remote portal and never changes.  Null while the project is pending first approval.",
                max_length=64,
                null=True,
                verbose_name="identifier",
            ),
        ),
        migrations.AddConstraint(
            model_name="remoteproject",
            constraint=models.UniqueConstraint(
                condition=models.Q(("identifier__isnull", False)),
                fields=("destination", "identifier"),
                name="unique_remote_project_destination_identifier",
            ),
        ),
        migrations.AddConstraint(
            model_name="remoteproject",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("current_project__isnull", False), ("identifier__isnull", True)
                ),
                fields=("destination", "current_project"),
                name="unique_pending_remote_project_destination_project",
            ),
        ),
    ]
