# Generated by Django 4.2.24 on 2026-05-07 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("waldur_openportal", "0038_alter_remoteproject_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remoteprojectauditentry",
            name="event_type",
            field=models.CharField(
                choices=[
                    (
                        "award_attempted",
                        "Award creation attempted but not yet confirmed (pending approval or error)",
                    ),
                    (
                        "award_rejected",
                        "Award creation explicitly rejected by remote portal",
                    ),
                    ("award_created", "Award created (create_award sent)"),
                    ("award_confirmed", "Award creation confirmed by remote portal"),
                    ("award_updated", "Award updated (update_award sent)"),
                    (
                        "award_update_confirmed",
                        "Award update confirmed by remote portal",
                    ),
                    ("award_update_rejected", "Award update rejected by remote portal"),
                    (
                        "award_fetched",
                        "Award details fetched from remote portal (get_award)",
                    ),
                    ("allocation_changed", "Allocation changed"),
                    ("allocation_confirmed", "Allocation change confirmed"),
                    ("allocation_rejected", "Allocation change rejected"),
                    ("project_attached", "Remote project attached to a local project"),
                    (
                        "project_detached",
                        "Remote project detached from a local project",
                    ),
                    ("state_changed", "State changed"),
                    ("resource_deleted", "Local resource deleted"),
                    ("resource_restored", "Local resource restored / reconnected"),
                ],
                db_index=True,
                max_length=32,
                verbose_name="event type",
            ),
        ),
        migrations.CreateModel(
            name="ManagedProjectAuditEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="Project identifier copied from ManagedProject at record time.",
                        max_length=64,
                        verbose_name="identifier",
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        help_text="Destination copied from ManagedProject at record time.",
                        max_length=256,
                        verbose_name="destination",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="timestamp"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Project request received"),
                            ("approved", "Project request approved"),
                            ("rejected", "Project request rejected"),
                            ("deleted", "ManagedProject deleted"),
                            ("note_added", "Note added"),
                            ("details_updated", "Award details updated"),
                            ("project_attached", "Waldur project attached"),
                            ("project_detached", "Waldur project detached"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="event type",
                    ),
                ),
                (
                    "previous_details",
                    models.JSONField(
                        blank=True,
                        help_text="Project details before this event.  Null for creation events.",
                        null=True,
                        verbose_name="previous details",
                    ),
                ),
                (
                    "new_details",
                    models.JSONField(
                        blank=True,
                        help_text="Project details after this event.  Null for events that do not change the details.",
                        null=True,
                        verbose_name="new details",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Optional free-text comment about this event.",
                        verbose_name="note",
                    ),
                ),
                (
                    "managed_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_log",
                        to="waldur_openportal.managedproject",
                        verbose_name="managed project",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who triggered this event, if it was a human action.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="performed by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Managed Project Audit Entry",
                "verbose_name_plural": "Managed Project Audit Entries",
                "ordering": ["-timestamp"],
            },
        ),
    ]
