# Generated by Django 4.2.24 on 2026-05-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_openportal", "0039_alter_remoteprojectauditentry_event_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="remoteproject",
            name="error_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The most recent rejection or error message received from the remote portal.  Cleared when the state transitions to ACTIVE.",
                verbose_name="error message",
            ),
        ),
    ]
