# Generated by Django 6.0.8 on 2026-09-15 09:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structure", "0041_squashed_0085"),
        ("waldur_openportal", "0001_squashed_0039"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagedProjectAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attached_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="attached at"
                    ),
                ),
                (
                    "detached_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Null while this is the current attachment.",
                        null=True,
                        verbose_name="detached at",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Optional comment - e.g. noting this row was reconstructed from ManagedProjectAuditEntry rather than recorded at the time.",
                        verbose_name="note",
                    ),
                ),
                (
                    "managed_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="waldur_openportal.managedproject",
                        verbose_name="managed project",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_project_attachments",
                        to="structure.project",
                        verbose_name="project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Managed Project Attachment",
                "verbose_name_plural": "Managed Project Attachments",
                "ordering": ["-attached_at"],
            },
        ),
    ]
