# Generated by Django 4.2.24 on 2026-05-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_openportal", "0040_remoteproject_error_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remoteprojectauditentry",
            name="event_type",
            field=models.CharField(
                choices=[
                    (
                        "award_attempted",
                        "Award creation attempted but not yet confirmed (pending approval or error)",
                    ),
                    (
                        "award_rejected",
                        "Award creation explicitly rejected by remote portal",
                    ),
                    ("award_created", "Award created (create_award sent)"),
                    ("award_updated", "Award updated (update_award sent)"),
                    (
                        "award_update_confirmed",
                        "Award update confirmed by remote portal",
                    ),
                    ("award_update_rejected", "Award update rejected by remote portal"),
                    ("state_changed", "State changed"),
                    ("resource_deleted", "Local resource deleted"),
                ],
                db_index=True,
                max_length=32,
                verbose_name="event type",
            ),
        ),
    ]
