# Generated by Django 6.0.8 on 2026-09-21 10:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_openportal", "0040_managedprojectattachment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="managedprojectattachment",
            options={
                "ordering": ["-attached_at", "-id"],
                "verbose_name": "Managed Project Attachment",
                "verbose_name_plural": "Managed Project Attachments",
            },
        ),
    ]
