# Generated by Django 4.2.24 on 2026-06-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_openportal", "0041_alter_remoteprojectauditentry_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remoteproject",
            name="notes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Append-only list of timestamped notes {timestamp, author, text}. Kept in sync with the full merged set from award_details() — includes both locally-authored notes and any notes added by the remote portal.",
                verbose_name="notes",
            ),
        ),
    ]
