# Generated by Django 6.0.8 on 2026-09-22 05:23

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_openportal", "0041_alter_managedprojectattachment_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="shortname",
            field=models.CharField(
                help_text="A short, unique name for you. It will be used to form your local username on any systems. Should only contain lower-case letters and digits and must start with a letter.",
                max_length=32,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Must start with a letter and only contain numbers and letters.",
                        regex="^[a-z][a-z0-9]+$",
                    ),
                    django.core.validators.RegexValidator(
                        flags=re.RegexFlag["IGNORECASE"],
                        inverse_match=True,
                        message="Cannot contain 'admin' or 'root'.",
                        regex="admin|root",
                    ),
                    django.core.validators.MinLengthValidator(4),
                    django.core.validators.MaxLengthValidator(32),
                ],
                verbose_name="shortname",
            ),
        ),
    ]
