# Generated by Django 6.0.8 on 2026-09-25 09:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_openportal", "0042_alter_userinfo_shortname"),
    ]

    operations = [
        migrations.AddField(
            model_name="remoteprojectattachment",
            name="project_identifier",
            field=models.CharField(
                blank=True,
                help_text="The local project identifier ({shortname}.{portal}) that this award's usage was fetched and cached under while attached. Null until recorded or backfilled.",
                max_length=64,
                null=True,
                verbose_name="project identifier",
            ),
        ),
        migrations.AlterField(
            model_name="remoteprojectattachment",
            name="attached_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="attached at"
            ),
        ),
    ]
