# Generated by Django 4.2.24 on 2026-06-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_openportal", "0042_alter_remoteproject_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remoteproject",
            name="allowed_domains",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="List of email domain glob patterns allowed to join the project on the remote portal, e.g. ['*.ac.uk']. None means all domains are allowed.",
                null=True,
                verbose_name="allowed domains",
            ),
        ),
    ]
