# Generated by Django 4.2.21 on 2025-06-04 07:48

import django.core.validators
from django.db import migrations, models

# This migration is the first step to removing the project.short_name field.
# It makes the field optional, allows it to be blank, and removes the
# uniqueness constraint. This field is replaced by waldur_openportal.ProjectInfo.shortname


class Migration(migrations.Migration):
    dependencies = [
        ("structure", "0052_accesssubnet_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="short_name",
            field=models.CharField(
                blank=True,
                help_text="A short, unique name for the project used as an identifier. Should only contain lower-case letters, digits, underscores and hyphens",
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(regex="^[a-z0-9\\-_]+$"),
                    django.core.validators.RegexValidator(
                        inverse_match=True, regex="(-admin)|(-root)$"
                    ),
                    django.core.validators.MinLengthValidator(3),
                    django.core.validators.MaxLengthValidator(30),
                ],
                verbose_name="short name",
            ),
        ),
    ]
