# Generated by Django 4.2.23 on 2025-06-12 06:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("structure", "0053_alter_project_short_name"),
        ("structure", "0053_customer_max_service_accounts_and_more"),
    ]

    operations = []
