# Generated by Django 4.2.24 on 2025-10-06 07:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("structure", "0054_merge_20250612_0633"),
        ("structure", "0061_customer_notification_emails"),
    ]

    operations = []
