# Generated by Django 4.2.24 on 2025-10-14 04:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("structure", "0062_customer_display_billing_info_in_projects"),
        ("structure", "0062_merge_20251006_0729"),
    ]

    operations = []
