# Generated by Django 4.2.24 on 2025-11-10 04:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("structure", "0063_merge_20251014_0410"),
        ("structure", "0066_alter_accesssubnet_options"),
    ]

    operations = []
