# Generated by Django 6.0.8 on 2026-09-23 09:08

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import waldur_core.core.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArchivedCall",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The original database row, verbatim.",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(blank=True)),
                ("description", models.CharField(blank=True, max_length=2000)),
                ("state", models.CharField(blank=True, max_length=10)),
                ("external_url", models.URLField(blank=True, null=True)),
                (
                    "reviewer_identity_visible_to_submitters",
                    models.BooleanField(default=False),
                ),
                ("reviews_visible_to_submitters", models.BooleanField(default=True)),
                (
                    "fixed_duration_in_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("manager_uuid", models.UUIDField(blank=True, null=True)),
                (
                    "customer_uuid",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("customer_name", models.CharField(blank=True, max_length=150)),
                ("created_by_uuid", models.UUIDField(blank=True, null=True)),
                ("created_by_username", models.CharField(blank=True, max_length=128)),
                ("created_by_full_name", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Archived call",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="ArchivedCallDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The original database row, verbatim.",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=2000)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="archived_call_documents"
                    ),
                ),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="proposal_archive.archivedcall",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archived call document",
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="ArchivedProposal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The original database row, verbatim.",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(blank=True)),
                ("description", models.CharField(blank=True, max_length=2000)),
                ("state", models.CharField(blank=True, max_length=10)),
                (
                    "duration_in_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("project_summary", models.TextField(blank=True)),
                (
                    "project_duration",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("project_is_confidential", models.BooleanField(default=False)),
                ("project_has_civilian_purpose", models.BooleanField(default=False)),
                ("oecd_fos_2007_code", models.CharField(blank=True, max_length=80)),
                (
                    "allocation_comment",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Call-manager notes: {timestamp, author, text}.",
                    ),
                ),
                (
                    "project_uuid",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("project_name", models.CharField(blank=True, max_length=150)),
                (
                    "created_by_uuid",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("created_by_username", models.CharField(blank=True, max_length=128)),
                ("created_by_full_name", models.CharField(blank=True, max_length=200)),
                ("approved_by_uuid", models.UUIDField(blank=True, null=True)),
                ("approved_by_username", models.CharField(blank=True, max_length=128)),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="proposal_archive.archivedcall",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archived proposal",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="ArchivedMembership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The original database row, verbatim.",
                    ),
                ),
                (
                    "scope_kind",
                    models.CharField(
                        choices=[
                            ("call", "Call"),
                            ("proposal", "Proposal"),
                            ("organisation", "Call managing organisation"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("organisation_customer_uuid", models.UUIDField(blank=True, null=True)),
                (
                    "organisation_customer_name",
                    models.CharField(blank=True, max_length=150),
                ),
                ("role_name", models.CharField(db_index=True, max_length=150)),
                ("role_description", models.CharField(blank=True, max_length=255)),
                ("user_uuid", models.UUIDField(blank=True, db_index=True, null=True)),
                ("user_username", models.CharField(blank=True, max_length=128)),
                ("user_full_name", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True, null=True)),
                ("expiration_time", models.DateTimeField(blank=True, null=True)),
                ("granted_by_username", models.CharField(blank=True, max_length=128)),
                ("revoked_by_username", models.CharField(blank=True, max_length=128)),
                ("revoke_reason", models.CharField(blank=True, max_length=255)),
                (
                    "call",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="proposal_archive.archivedcall",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="proposal_archive.archivedproposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archived membership",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="ArchivedProposalDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The original database row, verbatim.",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="archived_proposal_documentation",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="proposal_archive.archivedproposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archived proposal document",
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="ArchivedRequestedResource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The original database row, verbatim.",
                    ),
                ),
                ("offering_uuid", models.UUIDField(blank=True, null=True)),
                ("offering_name", models.CharField(blank=True, max_length=150)),
                ("plan_uuid", models.UUIDField(blank=True, null=True)),
                ("plan_name", models.CharField(blank=True, max_length=150)),
                ("template_name", models.CharField(blank=True, max_length=255)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                ("limits", models.JSONField(blank=True, default=dict)),
                ("resource_uuid", models.UUIDField(blank=True, null=True)),
                ("created_by_uuid", models.UUIDField(blank=True, null=True)),
                ("created_by_username", models.CharField(blank=True, max_length=128)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_resources",
                        to="proposal_archive.archivedproposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archived requested resource",
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="ArchivedReview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The original database row, verbatim.",
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=10)),
                ("summary_score", models.PositiveSmallIntegerField(default=0)),
                ("summary_public_comment", models.TextField(blank=True)),
                ("summary_private_comment", models.TextField(blank=True)),
                (
                    "comment_project_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "comment_project_summary",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "comment_project_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "comment_project_duration",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "comment_project_is_confidential",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "comment_project_has_civilian_purpose",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "comment_project_supporting_documentation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "comment_resource_requests",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "comment_team",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("reviewer_uuid", models.UUIDField(blank=True, null=True)),
                ("reviewer_username", models.CharField(blank=True, max_length=128)),
                ("reviewer_full_name", models.CharField(blank=True, max_length=200)),
                (
                    "comments",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Review conversation: {created, message}.",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="proposal_archive.archivedproposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archived review",
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="ArchivedRound",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The original database row, verbatim.",
                    ),
                ),
                ("slug", models.SlugField(blank=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("cutoff_time", models.DateTimeField(blank=True, null=True)),
                ("review_strategy", models.CharField(blank=True, max_length=20)),
                ("deciding_entity", models.CharField(blank=True, max_length=20)),
                ("allocation_time", models.CharField(blank=True, max_length=20)),
                ("allocation_date", models.DateTimeField(blank=True, null=True)),
                (
                    "review_duration_in_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("fixed_review_end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "minimum_number_of_reviewers",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "minimal_average_scoring",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "minimum_required_uploads",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="proposal_archive.archivedcall",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archived round",
                "ordering": ["-start_time"],
            },
        ),
        migrations.AddField(
            model_name="archivedproposal",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposals",
                to="proposal_archive.archivedround",
            ),
        ),
    ]
