# Generated by Django 6.0.8 on 2026-10-05 08:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("proposal_archive", "0002_unbound_copied_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="archivedcall",
            options={"ordering": ["-created", "id"], "verbose_name": "Archived call"},
        ),
        migrations.AlterModelOptions(
            name="archivedcalldocument",
            options={
                "ordering": ["created", "id"],
                "verbose_name": "Archived call document",
            },
        ),
        migrations.AlterModelOptions(
            name="archivedmembership",
            options={
                "ordering": ["-created", "id"],
                "verbose_name": "Archived membership",
            },
        ),
        migrations.AlterModelOptions(
            name="archivedproposal",
            options={
                "ordering": ["-created", "id"],
                "verbose_name": "Archived proposal",
            },
        ),
        migrations.AlterModelOptions(
            name="archivedproposaldocument",
            options={
                "ordering": ["created", "id"],
                "verbose_name": "Archived proposal document",
            },
        ),
        migrations.AlterModelOptions(
            name="archivedrequestedresource",
            options={
                "ordering": ["created", "id"],
                "verbose_name": "Archived requested resource",
            },
        ),
        migrations.AlterModelOptions(
            name="archivedreview",
            options={"ordering": ["created", "id"], "verbose_name": "Archived review"},
        ),
        migrations.AlterModelOptions(
            name="archivedround",
            options={
                "ordering": ["-start_time", "id"],
                "verbose_name": "Archived round",
            },
        ),
    ]
